#define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SOLID_COLOR
#define RGB_MATRIX_STARTUP_HUE 191
#define RGB_MATRIX_STARTUP_SAT 50
#define RGB_MATRIX_STARTUP_VAL 70
#define RGBLIGHT_SLEEP

#define GRAVE_ESC_ALT_OVERRIDE
#define GRAVE_ESC_CTRL_OVERRIDE
